### ISSUE TITLE
Where in mmtf is HELIX, SHEET, FORMUL information that is available in the pdb files?

### ISSUE THREAD

**Issue by yurivict** [rcsb/mmtf-cpp#28]
It doesn't seem to exist in mmtf, only in pdb: http://www.wwpdb.org/documentation/file-format-content/format33/v3.3.html

**Comment by gtauriello** [comment]
This a question for the MMTF repository where the format itself is defined and should be posed there and not here: https://github.com/rcsb/mmtf/issues

What I can say is that MMTF doesn't try to capture all of the mmCIF or PDB formats but a "large subset of the data" in there. Now, the secondary structure information is handled in the [secStructList](https://github.com/rcsb/mmtf/blob/v1.0/spec.md#secstructlist) field and chemical formulas are not mapped in MMTF at all. The recently added [extra fields](https://github.com/rcsb/mmtf/pull/36) might be a solution for any additional data you would like to store.

Since I couldn't transfer the issue in github (beta feature seems not to work as expected), I would ask you to continue the conversation in the MMTF repository.
