### ISSUE TITLE
Requires slightly newer version of msgpack-c

### ISSUE THREAD

**Issue by JarrettSJohnson** [rcsb/mmtf-cpp#7]
The usage of `MSGPACK_ZONE_ALIGNOF` in object_encoders.hpp seems as if it was introduced slightly after msgpack-c 2.1.1. (https://github.com/msgpack/msgpack-c/commit/288a6b2e315c2b89e0b9a8b6638044f50c3d7c89#diff-2e94eed119bc9c7356581907c785bd1e)

**Comment by danpf** [comment]
@gtauriello do you have anything against locking to 2.1.5?

3.0.1 came out, and we are compatible with that (at least... all tests pass)

**Comment by gtauriello** [comment]
I don't mind using 2.1.5. If it's ok with @JarrettSJohnson to use that version, I will just update the README here to require the newer version.

Otherwise, I guess we would have to revert to using MSGPACK_ZONE_ALIGN instead (not sure exactly what the effect of that change would be though).
@danpf the MSGPACK_ZONE_ALIGNOF macro was only used in object_encoders.hpp. Any comment on what it does? It does not seem to be particularly well documented in msgpack docs (unless I missed it).

**Comment by danpf** [comment]
it's a wrapper for the compiler function of __alignof__, I think if it's a problem we could just switch to that instead.

https://gcc.gnu.org/onlinedocs/gcc/Alignment.html

https://github.com/msgpack/msgpack-c/blob/0a65c443a260e835e36b4d94b00468d9df1551a2/include/msgpack/v1/detail/cpp11_zone_decl.hpp#L29

I just changed the call to __alignof__ and all the tests pass... but I really don't know enough about compiler object alignments to say if this is a good idea or not.

**Comment by JarrettSJohnson** [comment]
2.1.5 is fine and works. Thanks all.

**Comment by gtauriello** [comment]
@danpf given the define in msgpack, I guess that __alignof__ doesn't work in Windows...

Anyways: let's just stick to msgpack 2.1.5 and all good. I was going to just modify the README here, but we can do it with your other pull request. Makes sense indeed to lock the submodule versions to some release tag. I will close this here once we merged pull request #8.

**Comment by gtauriello** [comment]
Ok. Pull request #8 is closed so we can close this one too.
@JarrettSJohnson thanks again for pointing it out.
